In [2]:
a="now the time is "
b=1
print(a+str(b))

now the time is 1


In [13]:
a=input("Enter your name: ")
b=input("Enter your age: ")
c=f"I am,{b} years old is"
d="my name is",a,c
print(d.count("is"))
print(a.upper(),b.upper())
print(a.lower(),b.lower()) 

1
IS 33
is 33


In [10]:
a= "Saurodip Sinha"
print(a.split())

['Saurodip', 'Sinha']


In [14]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [15]:
mat2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(mat2)
print(mat2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [17]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8])
print(a.reshape(2,4))

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import pandas as pd
